"""Core data models for AdaRubric.

Defines the complete type hierarchy for tasks, trajectories, rubrics,
and evaluation results. All models use Pydantic v2 for runtime validation.
"""

from __future__ import annotations

import uuid
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, field_validator, model_validator

# ---------------------------------------------------------------------------
# Task representation
# ---------------------------------------------------------------------------


class TaskComplexity(str, Enum):
    SIMPLE = "simple"
    MODERATE = "moderate"
    COMPLEX = "complex"


class TaskDescription(BaseModel):
    """An agentic task whose trajectory will be evaluated."""

    task_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    instruction: str = Field(..., min_length=1)
    domain: str | None = None
    complexity: TaskComplexity = TaskComplexity.MODERATE
    context: dict[str, Any] = Field(default_factory=dict)
    expected_tools: list[str] | None = None


# ---------------------------------------------------------------------------
# Trajectory representation (Thought → Action → Observation)
# ---------------------------------------------------------------------------


class TrajectoryStep(BaseModel):
    """A single reasoning-action-observation step."""

    step_id: int = Field(..., ge=0)
    thought: str | None = None
    action: str
    action_input: dict[str, Any] | str = Field(default_factory=dict)
    observation: str

    @field_validator("action")
    @classmethod
    def _action_non_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("action must contain non-whitespace characters")
        return v


class Trajectory(BaseModel):
    """Complete multi-step agent trajectory."""

    trajectory_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    task_id: str
    steps: list[TrajectoryStep] = Field(..., min_length=1)
    final_answer: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def _validate_step_ordering(self) -> Trajectory:
        ids = [s.step_id for s in self.steps]
        if len(set(ids)) != len(ids):
            raise ValueError("step_ids must be unique")
        if ids != sorted(ids):
            raise ValueError("step_ids must be monotonically increasing")
        return self


# ---------------------------------------------------------------------------
# Dynamic rubric
# ---------------------------------------------------------------------------


class EvalDimension(BaseModel):
    """A single evaluation axis with a 5-point scoring rubric.

    Each dimension is task-specific and generated dynamically.
    The ``weight`` field allows non-uniform importance across dimensions.
    """

    name: str = Field(..., min_length=1, max_length=120)
    description: str = Field(..., min_length=10)
    weight: float = Field(default=1.0, gt=0.0)
    scoring_criteria: dict[int, str] = Field(
        ...,
        description="Mapping from score level (1-5) to concrete criteria",
    )

    @field_validator("scoring_criteria")
    @classmethod
    def _validate_criteria_keys(cls, v: dict[int, str]) -> dict[int, str]:
        expected = {1, 2, 3, 4, 5}
        if set(v.keys()) != expected:
            raise ValueError(
                f"scoring_criteria must have exactly keys {expected}, got {set(v.keys())}"
            )
        return v


class DynamicRubric(BaseModel):
    """Task-adaptive evaluation rubric containing N dimensions.

    Generated by a ``RubricGenerator`` based on the task description.
    Typically contains 3–5 orthogonal dimensions tailored to the task.
    """

    task_id: str
    dimensions: list[EvalDimension] = Field(..., min_length=1, max_length=10)
    generation_rationale: str = Field(
        default="",
        description="Explanation of why these dimensions were chosen",
    )

    @property
    def dimension_names(self) -> list[str]:
        return [d.name for d in self.dimensions]

    @property
    def total_weight(self) -> float:
        return sum(d.weight for d in self.dimensions)

    def get_dimension(self, name: str) -> EvalDimension | None:
        for d in self.dimensions:
            if d.name == name:
                return d
        return None


# ---------------------------------------------------------------------------
# Evaluation results
# ---------------------------------------------------------------------------


class DimensionScore(BaseModel):
    """Score on a single dimension for a single trajectory step."""

    dimension_name: str
    score: int = Field(..., ge=1, le=5)
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    rationale: str = Field(default="")


class StepEvaluation(BaseModel):
    """Per-step evaluation across all applicable dimensions."""

    step_id: int
    dimension_scores: list[DimensionScore] = Field(default_factory=list)
    step_quality_summary: str = Field(default="")

    @property
    def mean_score(self) -> float:
        if not self.dimension_scores:
            return 0.0
        return sum(s.score for s in self.dimension_scores) / len(self.dimension_scores)

    def score_for(self, dimension_name: str) -> DimensionScore | None:
        for ds in self.dimension_scores:
            if ds.dimension_name == dimension_name:
                return ds
        return None


class TrajectoryEvaluation(BaseModel):
    """Complete evaluation result for one trajectory.

    Contains step-level scores, per-dimension global scores,
    an overall global score, and a survival flag.
    """

    trajectory_id: str
    task_id: str
    rubric_used: DynamicRubric
    step_evaluations: list[StepEvaluation]
    dimension_global_scores: dict[str, float] = Field(default_factory=dict)
    global_score: float = Field(..., ge=0.0, le=5.0)
    passed_threshold: bool = False
    metadata: dict[str, Any] = Field(default_factory=dict)
